package com.tom.cpm.shared.network;

public enum ServerCaps {
	SCALING,
	EYE_HEIGHT,
	HITBOX_SCALING,
	MODEL_EVENT_SUBS,
	THIRD_PERSON,
	ATTRIBUTE_SCALE,
	GESTURES,
	PLUGIN_MESSAGES,
	INVIS_GLOW,
	NAMED_PARAMETERS,
	CPM_BUILT_IN_SERVER,
	CPM_CHUNKED_TRANSFER,
	CPM_TIME_BOUND_KEYS,
	;
	public static final ServerCaps[] VALUES = values();
}
